const screens=[...document.querySelectorAll('.screen')];
const state={stars:new Set(),conditionRound:0,loopTimes:null,mood:null,quiz:0,sound:true};
let audioContext;
function tone(freq,start,duration,type='sine',volume=.12){if(!state.sound)return;audioContext ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audioContext.currentTime+start);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+start+duration);o.connect(g).connect(audioContext.destination);o.start(audioContext.currentTime+start);o.stop(audioContext.currentTime+start+duration)}
function sound(name){if(name==='click'){tone(520,0,.08,'sine',.06);tone(720,.06,.1,'sine',.05)}if(name==='wrong'){tone(240,0,.14,'triangle',.08);tone(180,.13,.2,'triangle',.07)}if(name==='success'){[523,659,784,1047].forEach((f,i)=>tone(f,i*.1,.35,'triangle',.1))}if(name==='fanfare'){[523,659,784,1047,1319].forEach((f,i)=>tone(f,i*.12,.5,'triangle',.11));[262,392,523].forEach(f=>tone(f,.58,.75,'sine',.06))}}
document.querySelector('#soundToggle').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'🔊 Звук':'🔇 Звук';e.currentTarget.classList.toggle('muted',!state.sound);if(state.sound)sound('click')};
const concepts={
  algo:{definition:'<b>Линейный алгоритм</b> — это команды, которые выполняются одна за другой в определённом порядке.',kind:'sequence',steps:['⏰ Проснулся','🛏️ Встал с кровати','🚿 Умылся','🥣 Позавтракал','👕 Оделся','🎒 Пошёл в школу']},
  if:{definition:'<b>Алгоритм ветвления</b> — это алгоритм с выбором. Мы проверяем условие и выбираем один из двух путей: если ответ «да» — выполняем одно действие, если «нет» — другое.',kind:'branch'},
  repeat:{definition:'<b>Циклический алгоритм</b> — это алгоритм, в котором одна команда или несколько команд повторяются нужное количество раз.',kind:'birthday'}
};
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));scrollTo({top:0,behavior:'smooth'});sound('click')}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));
function renderConcept(key){const c=concepts[key];let visual='';if(c.kind==='sequence')visual=`<div class="daily-example"><span class="example-title">Пример: собираемся в школу</span><div class="visual-steps morning-steps">${c.steps.map((x,i)=>`${i?'<i>→</i>':''}<span>${x}</span>`).join('')}</div></div>`;if(c.kind==='branch')visual=`<div class="rain-example"><div class="condition-question"><small>УСЛОВИЕ</small><strong>На улице идёт дождь?</strong><span>🌧️</span></div><div class="rain-branches"><div class="branch-answer yes-answer"><b>ДА</b><span>☂️</span><p>Возьми зонт</p></div><div class="branch-answer no-answer"><b>НЕТ</b><span>☀️</span><p>Можно идти без зонта</p></div></div></div>`;if(c.kind==='birthday')visual=`<div class="birthday-example"><div class="birthday-scene"><span class="birthday-child">🧒</span><span class="birthday-cake">🎂</span><span class="birthday-family">👨‍👩‍👧</span></div><div class="cycle-arrow"><b>Празднуем день рождения</b><span>↻</span><strong>Проходит 365 дней</strong><span>↻</span><b>День рождения повторяется</b></div></div>`;document.querySelector('#explainCard').innerHTML=`<div class="concept-explanation"><div class="definition">${c.definition}</div>${visual}</div>`}
document.querySelectorAll('[data-concept]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-concept]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderConcept(b.dataset.concept)}));renderConcept('algo');
function addStar(name){state.stars.add(name);document.querySelector('#starCount').textContent=state.stars.size;burst();sound('success')}
function feedback(el,text,type='good'){el.textContent=text;el.className=`feedback show ${type}${el.classList.contains('inline')?' inline':''}`;if(type==='try')sound('wrong')}
function burst(){const box=document.querySelector('#confetti'),colors=['#ff657d','#ffca45','#6254e7','#35bce8','#45c58d'];for(let i=0;i<38;i++){const p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.background=colors[i%colors.length];p.style.animationDelay=Math.random()*.45+'s';p.style.transform=`rotate(${Math.random()*180}deg)`;box.append(p);setTimeout(()=>p.remove(),3500)}}

const linearCorrect=['basket','shelf','bread','put','cashier','pay'];
const linearData={basket:'🧺 Возьми корзину',shelf:'🚶 Подойди к полке',bread:'🍞 Возьми хлеб',put:'🛒 Положи в корзину',cashier:'🏁 Подойди к кассе',pay:'💳 Оплати'};
let linearChosen=[];
function renderLinear(){const bank=document.querySelector('#linearBank'),slots=document.querySelector('#linearSlots');bank.innerHTML='';slots.innerHTML='';Object.keys(linearData).sort(()=>Math.random()-.5).forEach(id=>{if(!linearChosen.includes(id))bank.append(commandButton(id))});linearChosen.forEach((id,index)=>{const b=commandButton(id);b.classList.add('selected');b.title='Нажмите, чтобы убрать';b.onclick=()=>{linearChosen.splice(index,1);renderLinear()};slots.append(b)});document.querySelector('#linearProgress').textContent=`${linearChosen.length} из 6`}
function commandButton(id){const b=document.createElement('button');b.className='command';b.textContent=linearData[id];b.onclick=()=>{if(!linearChosen.includes(id)){linearChosen.push(id);renderLinear()}};return b}
document.querySelector('#linearReset').onclick=()=>{linearChosen=[];renderLinear();document.querySelector('#linearFeedback').className='feedback';document.querySelector('#linearMessage').textContent='С чего начнём?'};
document.querySelector('#linearCheck').onclick=()=>{const out=document.querySelector('#linearFeedback');if(linearChosen.length<6)return feedback(out,'Сначала выбери все шесть команд. Ты справишься!','try');const wrong=linearChosen.findIndex((x,i)=>x!==linearCorrect[i]);if(wrong>=0)return feedback(out,`Робик запутался на шаге ${wrong+1}. Подумай, какая команда должна быть раньше.`,'try');const robot=document.querySelector('#linearRobot'),positions=['8%','25%','42%','58%','75%','83%'];linearChosen.forEach((_,i)=>setTimeout(()=>{robot.style.left=positions[i];document.querySelector('#linearMessage').textContent=linearData[linearChosen[i]]},i*430));setTimeout(()=>{feedback(out,'Отлично! Все команды стоят по порядку. Это линейный алгоритм! ⭐');addStar('linear');setTimeout(()=>show('condition'),1200)},linearChosen.length*430)};renderLinear();

const rounds=[{open:true,status:'ОТКРЫТО',story:'На двери зелёная табличка. Магазин открыт?'},{open:false,status:'ЗАКРЫТО',story:'Дверь закрыта, горит красная табличка. Магазин открыт?'}];
function renderCondition(){const r=rounds[state.conditionRound],scene=document.querySelector('#branchScene'),robik=document.querySelector('#branchRobik');document.querySelector('#conditionRound').textContent=state.conditionRound+1;document.querySelector('#storeStatus').textContent=r.status;document.querySelector('#storeStatus').classList.toggle('closed',!r.open);document.querySelector('#branchStory').textContent=r.story;scene.classList.toggle('night',!r.open);scene.querySelector('.sky-orb').textContent=r.open?'☀️':'🌙';robik.className='robik branch-robik';document.querySelector('#conditionFeedback').className='feedback inline'}
document.querySelectorAll('.branch-choice').forEach(b=>b.onclick=()=>{const r=rounds[state.conditionRound],correct=(b.dataset.choice==='yes')===r.open,out=document.querySelector('#conditionFeedback'),robik=document.querySelector('#branchRobik'),story=document.querySelector('#branchStory');if(!correct)return feedback(out,'Эта ветка не подходит к ситуации. Ещё раз проверь табличку на магазине.','try');sound('click');if(r.open){story.textContent='Ветка ДА: Робик входит и покупает молоко!';robik.classList.add('at-store');setTimeout(()=>{story.textContent='Молоко куплено. Робик возвращается домой.';robik.classList.remove('at-store');robik.classList.add('at-home')},1100)}else{story.textContent='Ветка НЕТ: Робик читает расписание.';robik.classList.add('at-store');setTimeout(()=>{story.textContent='Магазин закрыт. Робик вернётся завтра.';robik.classList.remove('at-store');robik.classList.add('at-home')},1100)}setTimeout(()=>{feedback(out,r.open?'Сработала ветка ДА: история продолжилась покупкой.':'Сработала ветка НЕТ: история пошла другим путём.');state.conditionRound++;if(state.conditionRound<rounds.length)setTimeout(renderCondition,950);else{addStar('condition');setTimeout(()=>show('loop'),1500)}},2300)});renderCondition();

document.querySelectorAll('[data-times]').forEach(b=>b.onclick=()=>{state.loopTimes=Number(b.dataset.times);document.querySelectorAll('[data-times]').forEach(x=>x.classList.toggle('selected',x===b))});
document.querySelector('#loopRun').onclick=()=>{const out=document.querySelector('#loopFeedback');if(!state.loopTimes)return feedback(out,'Сначала выбери, сколько раз повторить маршрут.','try');if(state.loopTimes!==3)return feedback(out,`Робик должен сходить в магазин 3 дня, а выбрано: ${state.loopTimes}. Попробуй ещё раз!`,'try');out.className='feedback inline';const robik=document.querySelector('#routeRobik'),scene=document.querySelector('#routeScene'),caption=document.querySelector('#routeCaption'),day=document.querySelector('#dayLabel'),sky=document.querySelector('#daySky'),apples=document.querySelector('#homeApples');let d=1;function runDay(){day.textContent=`День ${d}`;scene.classList.remove('night');sky.textContent='☀️';caption.textContent='Идёт в магазин';robik.classList.add('at-shop');setTimeout(()=>{caption.textContent='Покупает одно яблоко 🍎';sound('click')},1250);setTimeout(()=>{caption.textContent='Возвращается домой';robik.classList.remove('at-shop')},2050);setTimeout(()=>{apples.textContent='🍎'.repeat(d);caption.textContent=`Цикл ${d} завершён`;scene.classList.add('night');sky.textContent='🌙';if(d<3){d++;setTimeout(runDay,850)}else{setTimeout(()=>{feedback(out,'Маршрут «дом → магазин → дом» повторился три раза. Это цикл! ⭐');addStar('loop');setTimeout(()=>{show('finish');renderQuiz();sound('fanfare')},1500)},500)}},3350)}runDay()};

const quiz=[{q:'«Возьми корзину → выбери товар → подойди к кассе»',a:'Алгоритм'},{q:'«Если есть карта — оплати картой, иначе — наличными»',a:'Условие'},{q:'«Повтори три раза: положи яблоко в пакет»',a:'Цикл'}];
function renderQuiz(){const item=quiz[state.quiz];if(!item){document.querySelector('#quizCard').textContent='🎉 Все ответы правильные!';document.querySelector('#quizChoices').innerHTML='';feedback(document.querySelector('#quizFeedback'),'Ты различаешь алгоритм, условие и цикл!');return}document.querySelector('#quizCard').textContent=item.q;const choices=['Алгоритм','Условие','Цикл'];document.querySelector('#quizChoices').innerHTML=choices.map(x=>`<button data-quiz="${x}">${x}</button>`).join('');document.querySelector('#quizFeedback').className='feedback inline';document.querySelectorAll('[data-quiz]').forEach(b=>b.onclick=()=>{if(b.dataset.quiz===item.a){feedback(document.querySelector('#quizFeedback'),'Правильно!','good');state.quiz++;setTimeout(renderQuiz,550)}else feedback(document.querySelector('#quizFeedback'),'Подумай ещё немного — ищи слова-подсказки.','try')})}
document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{state.mood=b.dataset.mood;document.querySelectorAll('[data-mood]').forEach(x=>x.classList.toggle('selected',x===b))});
document.querySelector('#saveReflection').onclick=()=>{const thanks=document.querySelector('#reflectionThanks');if(!state.mood){thanks.style.color='#b7681b';thanks.textContent='Сначала выбери один стикер 🙂';return}const entry={mood:state.mood,wish:document.querySelector('#wishText').value.trim(),date:new Date().toISOString()};const old=JSON.parse(localStorage.getItem('smartMarketReflections')||'[]');old.push(entry);localStorage.setItem('smartMarketReflections',JSON.stringify(old));thanks.style.color='';thanks.textContent='Спасибо! Твой стикер уже в Корзине знаний 🛒';burst()};
document.querySelector('#restart').onclick=()=>location.reload();
document.querySelector('#openReflection').onclick=()=>show('reflection');
const proReturn=document.querySelector('#proReturn'),megaReward=document.querySelector('#megaReward');
document.querySelector('#launchPro').onclick=()=>{sound('fanfare');localStorage.setItem('computeItStarted','1');proReturn.classList.add('show');window.open('https://compute-it.toxicode.fr/','_blank','noopener,noreferrer')};
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&localStorage.getItem('computeItStarted')==='1')proReturn.classList.add('show')});
document.querySelector('#claimPro').onclick=()=>{megaReward.classList.add('show');proReturn.classList.remove('show');localStorage.setItem('computeItReward','5');burst();burst();sound('fanfare');setTimeout(()=>megaReward.scrollIntoView({behavior:'smooth',block:'center'}),100)};
if(localStorage.getItem('computeItReward')==='5')megaReward.classList.add('show');
renderQuiz();
